### ISSUE TITLE
NHF: Hard to find because Google cannot index the app

### ISSUE THREAD

**Issue by radl97** [leventeBajczi/mobweb#1]
From.the manifest file:

`tools:ignore="GoogleAppIndexingWarning"`

This warning means that there is no (easy) way to find (and install) the app, because no keywords are defined.

Solution: select the other way to fix the warning 😛

Workaround: go to playstore, select a random app, and rewrite app ID to hu.bme.aut.xcfatest

(So the statement that "this app can be *found* on Play Store" is a bit overestimation :p )

**Comment by leventeBajczi** [comment]
https://play.google.com/store/apps/details?id=hu.bme.aut.xcfatest
I can find it just fine, but sure, this is valid :smile: 
Won't fix though.
